### ISSUE TITLE
Make the navbar logo change according to dark/light theme

### ISSUE THREAD

**Issue by LakinduK** [LakinduK/hacktoberfest2022#1]
I have added two dark and light hacktoberfest logos in "contributors/src/H22" folder as:
1. [H22-logo-dark.png](https://github.com/LakinduK/hacktoberfest2022/blob/main/contributors/src/H22/H22-logo-dark.png)
2. [H22-logo-light.png](https://github.com/LakinduK/hacktoberfest2022/blob/main/contributors/src/H22/H22-logo-light.png)

logo is currently on dark mode only.
Use them and figure out a way to set it according to color theme.

**Comment by Ved142** [comment]
Hey @LakinduK I would like to work on it. Please assign it to me.

**Comment by LakinduK** [comment]
> Hey @LakinduK I would like to work on it. Please assign it to me.

nice!

**Comment by Ved142** [comment]
@LakinduK , I have solved this issue now you can review my pull request.
