### ISSUE TITLE
Navbar isn't mobile responsive 

### ISSUE THREAD

**Issue by LakinduK** [LakinduK/hacktoberfest2022#10]
Navbar in this website looks good on desktop/laptop devices but if you view https://lakinduk.github.io/hacktoberfest2022/contributors/ in a mobile, it looks weird. ☹️

![image](https://user-images.githubusercontent.com/38062348/196735125-23c54b46-24a7-401c-9653-13cee1b3418f.png)

### Note:  💡
* I have used Bootstrap 5.1 to stylize and maintain responsive UI. 
Please refer the documentation of [Bootstrap 5.1](https://getbootstrap.com/docs/5.2/getting-started/introduction/) to make the navbar responsive.
* Try to add a [collapsing navbar](https://getbootstrap.com/docs/5.1/components/navbar/#responsive-behaviors) to collapse buttons on mobile.

**Comment by vaibhav-009** [comment]
please assign this to me

**Comment by LakinduK** [comment]
This issue is fixed by @vaibhav-009.
