### ISSUE TITLE
Change footer color

### ISSUE THREAD

**Issue by LakinduK** [LakinduK/hacktoberfest2022#12]
![image](https://user-images.githubusercontent.com/38062348/196737856-ea42e357-917d-40e8-b0c4-142a18152bee.png)

Notice the footer is in two colors? ☹
It would be very helpful if someone can fix it!

**Comment by shaikshahid98** [comment]
@LakinduK  please assign this to me.

**Comment by shaikshahid98** [comment]
Fixed it. Just working on other issues.

**Comment by TBill06** [comment]
Hi, This is my first contribution, I've already opened a PR, let me know if it is correct. Thanks

**Comment by LakinduK** [comment]
Hi guys!
Really appreciate the effort towards fixing the error. 😍
However,
What I wanted is to fix the footer color change according to theme color. (Color must be switched according to for dark mode and light mode)
Give it another try. 😎

**Comment by shaikshahid98** [comment]
Done. Made the footer color as Black and text color as white and viceversa in Light mode.
