### ISSUE TITLE
In Light-Theme hacktoberfest banner is not visible

### ISSUE THREAD

**Issue by LakinduK** [LakinduK/hacktoberfest2022#4]
In the Dark-Theme  [H22-Banners-Dark.png](https://github.com/LakinduK/hacktoberfest2022/blob/main/contributors/src/H22/H22-Banners-Dark.png) is visible but in Light-Theme [H22-Banners-Light.png](https://github.com/LakinduK/hacktoberfest2022/blob/main/contributors/src/H22/H22-Banners-Light.png) doesn't load up. 

quick tips:
* I've noticed images are not optimized (some are 9MB+).
* Maybe invalid paths.

**Comment by shaikshahid98** [comment]
Hi LakinduK,

I am new to open source and I really want to contribute to this issue. Please assign it to me. And I am gonna start working on it 
right away.

-Shaik
